import os
import google.generativeai as genai
from dotenv import load_dotenv

# Explicitly Load Environment Variables
load_dotenv()

# Configure the Gemini API Key
api_key = os.getenv("GEMINI_API_KEY")
if not api_key:
    raise ValueError("❌ GEMINI_API_KEY is not set. Please verify your .env file.")

genai.configure(api_key=api_key)

def get_gemini_feedback(activity_data):
    """
    Analyze weekly activity data and generate tailored feedback using Gemini API.
    """
    try:
        print("🔄 Sending data to Gemini for analysis...")

        # Initialize Gemini Model
        model = genai.GenerativeModel('gemini-pro')

        # Generate Feedback
        response = model.generate_content(
            f"You are an assistant analyzing weekly activity reports. Analyze the following weekly activities and provide feedback:\n{activity_data}"
        )

        # Extract Response Text
        feedback = response.text.strip()
        print("✅ Feedback successfully generated by Gemini.")
        return feedback

    except genai.types.APIError as e:
        print(f"❌ API Error: {e.message}")
        return "⚠️ Feedback generation failed due to an API error."
    except genai.types.PermissionDenied as e:
        print("❌ Permission Denied: Verify API key permissions in Google AI Studio.")
        return "⚠️ Permission error. Check API key permissions."
    except Exception as e:
        print(f"❌ An unexpected error occurred: {e}")
        return "⚠️ Feedback generation failed. Check logs for details."

# Testing the Gemini Feedback Function
if __name__ == "__main__":
    sample_data = """
    - Outreach Officer: Recruited 5 clients, contacted 10 potential volunteers.
    - Developer: Worked 15 hours on the website redesign.
    """
    feedback = get_gemini_feedback(sample_data)
    print("📝 Gemini Feedback:\n", feedback)
